# Should be mounted in /etc/nginx/sites-enabled
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: scylla-services-nginx-sites-config
  namespace: scylla
data:
  default: |
    server {
        listen 80;
        add_header X-Frame-Options SAMEORIGIN always;
        add_header Strict-Transport-Security "max-age=31536000; includeSubDomains" always;

        add_header Last-Modified $date_gmt;
        add_header Cache-Control 'no-store, no-cache, must-revalidate, proxy-revalidate, max-age=0';
        if_modified_since off;
        expires off;
        etag off;

        root /usr/share/nginx/html;
        index index.html;

        server_tokens  off; # disable the Server nginx header

        server_name _;

        #if ($http_x_forwarded_proto = 'http') {
        #   return 301 https://$host$request_uri;
        #}

        # enable gzip
        gzip on;
        gzip_disable "msie6";

        gzip_comp_level 6;
        gzip_min_length 1100;
        gzip_buffers 16 8k;
        gzip_proxied any;
        gzip_types
            text/plain
            text/css
            text/js
            text/xml
            text/javascript
            application/javascript
            application/x-javascript
            application/json
            application/xml
            application/rss+xml
            image/svg+xml;

        location / {
            try_files $uri /index.html; # redirect all request to index.html

            add_header X-Frame-Options SAMEORIGIN always;
            add_header Strict-Transport-Security "max-age=31536000; includeSubDomains" always;

            add_header Last-Modified $date_gmt;
            add_header Cache-Control 'no-store, no-cache, must-revalidate, proxy-revalidate, max-age=0';
            if_modified_since off;
            expires off;
            etag off;
        }
        location ~ ^/(api|archive) {
            proxy_pass http://127.0.0.1:8090;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Host $server_name;
        }
        location /socket.io {
             proxy_pass  http://127.0.0.1:8090;
             proxy_set_header  Host $host;
             proxy_set_header  X-Real-IP $remote_addr;
             proxy_set_header  X-Forwarded-For $proxy_add_x_forwarded_for;
             proxy_set_header  X-Forwarded-Host $server_name;
             proxy_pass_request_headers on;
             proxy_set_header Upgrade $http_upgrade;
             proxy_set_header Connection "Upgrade";
             proxy_set_header Host $host;
       }
    }